version: '2.0'
services:
    fhir_validator_config:
        ports:
            - '4435:4849'
        volumes:
            - '/home/riro/Scratch/data:/home/service/data'
            - '/home/riro/Technical_Specialist_Folder/fhir/Assets/NHSD.Assets.STU3_1.4.0/node_modules/NHSD.Assets.STU3:/home/service/fhir/STU3'
            - '/home/riro/Technical_Specialist_Folder/fhir/Assets/UKCore.R4.STU.02.00.00/package:/home/service/fhir/R4'
        image: 'nhsdigitalmait/fhir_validator_config:20210805'
