FROM nhsdigitalmait/tkw-x:a3450be
RUN useradd -rm -u 1000 service

ENV TKWROOT=/home/service/TKW
ENV FHIR_ASSETS_NPMTAR_ROOT=/home/service/fhir
ENV TERMINOLOGY_SERVER_ACCESS_TOKEN_ROOT=/home/service/access_token

RUN mkdir /home/service/data/ \
    && mkdir /home/service/certs/ \
    && mkdir /home/service/fhir/ \
    && mkdir /home/service/access_token/ \
    && chown service:service /home/service
COPY . /home/service/TKW/config/FHIR_VALIDATOR_SERVER
WORKDIR /home/service/TKW/config/FHIR_VALIDATOR_SERVER
RUN mkdir /home/service/TKW/config/FHIR_VALIDATOR_SERVER/simulator_saved_messages/
RUN mkdir /home/service/TKW/config/FHIR_VALIDATOR_SERVER/messages_for_validation/
RUN mkdir /home/service/TKW/config/FHIR_VALIDATOR_SERVER/transmitter_sent_messages/
RUN chown service:service -R /home/service
RUN sh set-all-configurations.sh
ENV trustStore=default
ENV trustStorePassword=default
ENV keyStore=default
ENV keyStorePassword=default
USER service
CMD ["bash", "runtkwfhirvalidator.sh"]
