version: '2.0'
services:
    fhir_validator_config:
        network_mode : "host"
        volumes:
            # external configuration directory
            - '${TKWROOT}/config/FHIR_VALIDATOR_SERVER/external_configs:/home/service/TKW/config/FHIR_VALIDATOR_SERVER/external_configs'
            # data directory
            - '${HOME}/Scratch/data:/home/service/data'
            # directory for storing evidence
            - '${TKWROOT}/config/FHIR_VALIDATOR_SERVER/all_evidence:/home/service/TKW/config/FHIR_VALIDATOR_SERVER/all_evidence'
            # log directory for TKW logs
            - '${TKWROOT}/config/FHIR_VALIDATOR_SERVER/logs:/home/service/TKW/config/FHIR_VALIDATOR_SERVER/logs'
            # asset directory for reading npm tars
            - '${HOME}/Technical_Specialist_Folder/fhir/Assets/npm_tars:/home/service/fhir'
            # Access token file location for the remote terminology server
            - '${HOME}/Technical_Specialist_Folder/TerminologyServer/TerminologyServerLoginDetails:/home/service/access_token'
        image: 'nhsdigitalmait/fhir_validator_config:20220615'
